- set_fact:
    private_key: "{{ key_path }}/ssh_host_{{ key_type }}_key"
    public_key: "{{ key_path }}/ssh_host_{{ key_type }}_key.pub"

- shell: "grep -qE '^.* root@{{ template_hostname }}$' {{ public_key }}"
  delegate_to: "{{ template_hostname }}"
  changed_when: False
  failed_when: False
  register: host_key_template

- name:  "Remove existing ssh private host key {{ private_key }}"
  file:
    path: "{{ private_key }}"
    state: absent
  become: True
  delegate_to: "{{ template_hostname }}"
  when: host_key_template.rc == 0

- name:  "Remove existing ssh public host key {{ public_key }}"
  file:
    path: "{{ public_key }}"
    state: absent
  become: True
  delegate_to: "{{ template_hostname }}"
  when: host_key_template.rc == 0

- name: "Create new ssh host key {{ private_key }}"
  command: "ssh-keygen -q -t {{ key_type }} -f {{ private_key }} -C \"\" -N \"\""
  args:
    creates: "{{ private_key }}"
  become: True
  delegate_to: "{{ template_hostname }}"
  when: host_key_template.rc == 0

